# Generated by Django 3.0.3 on 2020-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
                ('units', models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Available Units')),
                ('genre', models.PositiveSmallIntegerField(choices=[('TERROR', 1), ('ACCION', 2)], default=2, verbose_name='Genre')),
            ],
        ),
    ]
