# Generated by Django 3.0.3 on 2020-02-27 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('birht_date', models.DateField(blank=True, verbose_name='Birth Date')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled', max_length=40, verbose_name='Title')),
                ('units', models.DecimalField(decimal_places=0, default=1, max_digits=4, verbose_name='Available Units')),
                ('genre', models.PositiveSmallIntegerField(choices=[(2, 'ACCION'), (1, 'TERROR')], default=2, verbose_name='Genre')),
                ('director_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='movie', to='movies.Director')),
            ],
        ),
    ]
