# Generated by Django 3.0.3 on 2020-02-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(null=True, upload_to='.', verbose_name='Poster'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(4, 'THRILLER'), (2, 'ACTION'), (1, 'TERROR'), (3, 'DRAMA')], default=2, verbose_name='Genre'),
        ),
    ]
