# Generated by Django 3.0.3 on 2020-02-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(default='undefined', max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.PositiveSmallIntegerField(choices=[(2, 'ACCION'), (1, 'TERROR')], default=2, verbose_name='Genre'),
        ),
    ]
