# Generated by Django 3.0.3 on 2020-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20200227_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='name',
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='untitled', max_length=40, verbose_name='Title'),
        ),
    ]
