# Generated by Django 3.0.3 on 2020-02-28 19:02

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20200228_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[(movies.models.Genre['TERROR'], 'TERROR'), (movies.models.Genre['ACTION'], 'ACTION'), (movies.models.Genre['DRAMA'], 'DRAMA'), (movies.models.Genre['THRILLER'], 'THRILLER')], default=movies.models.Genre['ACTION'], max_length=20, verbose_name='Genre'),
        ),
    ]
