# Generated by Django 3.0.3 on 2020-03-01 17:26

from django.db import migrations, models
import movies.models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20200228_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AddField(
            model_name='movie',
            name='voters',
            field=models.IntegerField(default=0, verbose_name='Voters'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('TERROR', 'TERROR'), ('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('THRILLER', 'THRILLER')], default=movies.models.Genre['ACTION'], max_length=20, verbose_name='Genre'),
        ),
    ]
