# Generated by Django 3.0.3 on 2020-03-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20200301_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='units',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)], verbose_name='Available Units'),
        ),
    ]
